//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace LWP.Lib
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class YusongCompanyEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new YusongCompanyEntities object using the connection string found in the 'YusongCompanyEntities' section of the application configuration file.
        /// </summary>
        public YusongCompanyEntities() : base("name=YusongCompanyEntities", "YusongCompanyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new YusongCompanyEntities object.
        /// </summary>
        public YusongCompanyEntities(string connectionString) : base(connectionString, "YusongCompanyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new YusongCompanyEntities object.
        /// </summary>
        public YusongCompanyEntities(EntityConnection connection) : base(connection, "YusongCompanyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<About> Abouts
        {
            get
            {
                if ((_Abouts == null))
                {
                    _Abouts = base.CreateObjectSet<About>("Abouts");
                }
                return _Abouts;
            }
        }
        private ObjectSet<About> _Abouts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Brand> Brands
        {
            get
            {
                if ((_Brands == null))
                {
                    _Brands = base.CreateObjectSet<Brand>("Brands");
                }
                return _Brands;
            }
        }
        private ObjectSet<Brand> _Brands;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Dictionary> Dictionaries
        {
            get
            {
                if ((_Dictionaries == null))
                {
                    _Dictionaries = base.CreateObjectSet<Dictionary>("Dictionaries");
                }
                return _Dictionaries;
            }
        }
        private ObjectSet<Dictionary> _Dictionaries;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Language> Languages
        {
            get
            {
                if ((_Languages == null))
                {
                    _Languages = base.CreateObjectSet<Language>("Languages");
                }
                return _Languages;
            }
        }
        private ObjectSet<Language> _Languages;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<News> News
        {
            get
            {
                if ((_News == null))
                {
                    _News = base.CreateObjectSet<News>("News");
                }
                return _News;
            }
        }
        private ObjectSet<News> _News;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Product> Products
        {
            get
            {
                if ((_Products == null))
                {
                    _Products = base.CreateObjectSet<Product>("Products");
                }
                return _Products;
            }
        }
        private ObjectSet<Product> _Products;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProductClass> ProductClasses
        {
            get
            {
                if ((_ProductClasses == null))
                {
                    _ProductClasses = base.CreateObjectSet<ProductClass>("ProductClasses");
                }
                return _ProductClasses;
            }
        }
        private ObjectSet<ProductClass> _ProductClasses;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Abouts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAbouts(About about)
        {
            base.AddObject("Abouts", about);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Brands EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBrands(Brand brand)
        {
            base.AddObject("Brands", brand);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Dictionaries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDictionaries(Dictionary dictionary)
        {
            base.AddObject("Dictionaries", dictionary);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Languages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLanguages(Language language)
        {
            base.AddObject("Languages", language);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the News EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNews(News news)
        {
            base.AddObject("News", news);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Products EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProducts(Product product)
        {
            base.AddObject("Products", product);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProductClasses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProductClasses(ProductClass productClass)
        {
            base.AddObject("ProductClasses", productClass);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="YusongCompanyModel", Name="About")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class About : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new About object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static About CreateAbout(global::System.Int32 id)
        {
            About about = new About();
            about.Id = id;
            return about;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Context
        {
            get
            {
                return _Context;
            }
            set
            {
                OnContextChanging(value);
                ReportPropertyChanging("Context");
                _Context = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Context");
                OnContextChanged();
            }
        }
        private global::System.String _Context;
        partial void OnContextChanging(global::System.String value);
        partial void OnContextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DictLangId
        {
            get
            {
                return _DictLangId;
            }
            set
            {
                OnDictLangIdChanging(value);
                ReportPropertyChanging("DictLangId");
                _DictLangId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DictLangId");
                OnDictLangIdChanged();
            }
        }
        private Nullable<global::System.Int32> _DictLangId;
        partial void OnDictLangIdChanging(Nullable<global::System.Int32> value);
        partial void OnDictLangIdChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="YusongCompanyModel", Name="Brand")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Brand : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Brand object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Brand CreateBrand(global::System.Int32 id)
        {
            Brand brand = new Brand();
            brand.Id = id;
            return brand;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String logo
        {
            get
            {
                return _logo;
            }
            set
            {
                OnlogoChanging(value);
                ReportPropertyChanging("logo");
                _logo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("logo");
                OnlogoChanged();
            }
        }
        private global::System.String _logo;
        partial void OnlogoChanging(global::System.String value);
        partial void OnlogoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SortVal
        {
            get
            {
                return _SortVal;
            }
            set
            {
                OnSortValChanging(value);
                ReportPropertyChanging("SortVal");
                _SortVal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SortVal");
                OnSortValChanged();
            }
        }
        private Nullable<global::System.Int32> _SortVal;
        partial void OnSortValChanging(Nullable<global::System.Int32> value);
        partial void OnSortValChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsShow
        {
            get
            {
                return _IsShow;
            }
            set
            {
                OnIsShowChanging(value);
                ReportPropertyChanging("IsShow");
                _IsShow = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsShow");
                OnIsShowChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsShow;
        partial void OnIsShowChanging(Nullable<global::System.Boolean> value);
        partial void OnIsShowChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DictLangId
        {
            get
            {
                return _DictLangId;
            }
            set
            {
                OnDictLangIdChanging(value);
                ReportPropertyChanging("DictLangId");
                _DictLangId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DictLangId");
                OnDictLangIdChanged();
            }
        }
        private Nullable<global::System.Int32> _DictLangId;
        partial void OnDictLangIdChanging(Nullable<global::System.Int32> value);
        partial void OnDictLangIdChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="YusongCompanyModel", Name="Dictionary")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Dictionary : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Dictionary object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Dictionary CreateDictionary(global::System.Int32 id)
        {
            Dictionary dictionary = new Dictionary();
            dictionary.Id = id;
            return dictionary;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DictToken
        {
            get
            {
                return _DictToken;
            }
            set
            {
                OnDictTokenChanging(value);
                ReportPropertyChanging("DictToken");
                _DictToken = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DictToken");
                OnDictTokenChanged();
            }
        }
        private global::System.String _DictToken;
        partial void OnDictTokenChanging(global::System.String value);
        partial void OnDictTokenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DictText
        {
            get
            {
                return _DictText;
            }
            set
            {
                OnDictTextChanging(value);
                ReportPropertyChanging("DictText");
                _DictText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DictText");
                OnDictTextChanged();
            }
        }
        private global::System.String _DictText;
        partial void OnDictTextChanging(global::System.String value);
        partial void OnDictTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DictLangId
        {
            get
            {
                return _DictLangId;
            }
            set
            {
                OnDictLangIdChanging(value);
                ReportPropertyChanging("DictLangId");
                _DictLangId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DictLangId");
                OnDictLangIdChanged();
            }
        }
        private Nullable<global::System.Int32> _DictLangId;
        partial void OnDictLangIdChanging(Nullable<global::System.Int32> value);
        partial void OnDictLangIdChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="YusongCompanyModel", Name="Language")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Language : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Language object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Language CreateLanguage(global::System.Int32 id)
        {
            Language language = new Language();
            language.Id = id;
            return language;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="YusongCompanyModel", Name="News")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class News : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new News object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static News CreateNews(global::System.Int32 id)
        {
            News news = new News();
            news.Id = id;
            return news;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Context
        {
            get
            {
                return _Context;
            }
            set
            {
                OnContextChanging(value);
                ReportPropertyChanging("Context");
                _Context = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Context");
                OnContextChanged();
            }
        }
        private global::System.String _Context;
        partial void OnContextChanging(global::System.String value);
        partial void OnContextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Author
        {
            get
            {
                return _Author;
            }
            set
            {
                OnAuthorChanging(value);
                ReportPropertyChanging("Author");
                _Author = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Author");
                OnAuthorChanged();
            }
        }
        private global::System.String _Author;
        partial void OnAuthorChanging(global::System.String value);
        partial void OnAuthorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Summary
        {
            get
            {
                return _Summary;
            }
            set
            {
                OnSummaryChanging(value);
                ReportPropertyChanging("Summary");
                _Summary = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Summary");
                OnSummaryChanged();
            }
        }
        private global::System.String _Summary;
        partial void OnSummaryChanging(global::System.String value);
        partial void OnSummaryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsShow
        {
            get
            {
                return _IsShow;
            }
            set
            {
                OnIsShowChanging(value);
                ReportPropertyChanging("IsShow");
                _IsShow = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsShow");
                OnIsShowChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsShow;
        partial void OnIsShowChanging(Nullable<global::System.Boolean> value);
        partial void OnIsShowChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DictLangId
        {
            get
            {
                return _DictLangId;
            }
            set
            {
                OnDictLangIdChanging(value);
                ReportPropertyChanging("DictLangId");
                _DictLangId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DictLangId");
                OnDictLangIdChanged();
            }
        }
        private Nullable<global::System.Int32> _DictLangId;
        partial void OnDictLangIdChanging(Nullable<global::System.Int32> value);
        partial void OnDictLangIdChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="YusongCompanyModel", Name="Product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Product CreateProduct(global::System.Int32 id)
        {
            Product product = new Product();
            product.Id = id;
            return product;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ClassId
        {
            get
            {
                return _ClassId;
            }
            set
            {
                OnClassIdChanging(value);
                ReportPropertyChanging("ClassId");
                _ClassId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClassId");
                OnClassIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ClassId;
        partial void OnClassIdChanging(Nullable<global::System.Int32> value);
        partial void OnClassIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Describe
        {
            get
            {
                return _Describe;
            }
            set
            {
                OnDescribeChanging(value);
                ReportPropertyChanging("Describe");
                _Describe = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Describe");
                OnDescribeChanged();
            }
        }
        private global::System.String _Describe;
        partial void OnDescribeChanging(global::System.String value);
        partial void OnDescribeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Attachment
        {
            get
            {
                return _Attachment;
            }
            set
            {
                OnAttachmentChanging(value);
                ReportPropertyChanging("Attachment");
                _Attachment = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Attachment");
                OnAttachmentChanged();
            }
        }
        private Nullable<global::System.Int32> _Attachment;
        partial void OnAttachmentChanging(Nullable<global::System.Int32> value);
        partial void OnAttachmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String thumbnail
        {
            get
            {
                return _thumbnail;
            }
            set
            {
                OnthumbnailChanging(value);
                ReportPropertyChanging("thumbnail");
                _thumbnail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("thumbnail");
                OnthumbnailChanged();
            }
        }
        private global::System.String _thumbnail;
        partial void OnthumbnailChanging(global::System.String value);
        partial void OnthumbnailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String price
        {
            get
            {
                return _price;
            }
            set
            {
                OnpriceChanging(value);
                ReportPropertyChanging("price");
                _price = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("price");
                OnpriceChanged();
            }
        }
        private global::System.String _price;
        partial void OnpriceChanging(global::System.String value);
        partial void OnpriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsHot
        {
            get
            {
                return _IsHot;
            }
            set
            {
                OnIsHotChanging(value);
                ReportPropertyChanging("IsHot");
                _IsHot = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsHot");
                OnIsHotChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsHot;
        partial void OnIsHotChanging(Nullable<global::System.Boolean> value);
        partial void OnIsHotChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsRecommend
        {
            get
            {
                return _IsRecommend;
            }
            set
            {
                OnIsRecommendChanging(value);
                ReportPropertyChanging("IsRecommend");
                _IsRecommend = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsRecommend");
                OnIsRecommendChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsRecommend;
        partial void OnIsRecommendChanging(Nullable<global::System.Boolean> value);
        partial void OnIsRecommendChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BrandId
        {
            get
            {
                return _BrandId;
            }
            set
            {
                OnBrandIdChanging(value);
                ReportPropertyChanging("BrandId");
                _BrandId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BrandId");
                OnBrandIdChanged();
            }
        }
        private Nullable<global::System.Int32> _BrandId;
        partial void OnBrandIdChanging(Nullable<global::System.Int32> value);
        partial void OnBrandIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsShow
        {
            get
            {
                return _IsShow;
            }
            set
            {
                OnIsShowChanging(value);
                ReportPropertyChanging("IsShow");
                _IsShow = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsShow");
                OnIsShowChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsShow;
        partial void OnIsShowChanging(Nullable<global::System.Boolean> value);
        partial void OnIsShowChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Attr1
        {
            get
            {
                return _Attr1;
            }
            set
            {
                OnAttr1Changing(value);
                ReportPropertyChanging("Attr1");
                _Attr1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Attr1");
                OnAttr1Changed();
            }
        }
        private global::System.String _Attr1;
        partial void OnAttr1Changing(global::System.String value);
        partial void OnAttr1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Attr2
        {
            get
            {
                return _Attr2;
            }
            set
            {
                OnAttr2Changing(value);
                ReportPropertyChanging("Attr2");
                _Attr2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Attr2");
                OnAttr2Changed();
            }
        }
        private global::System.String _Attr2;
        partial void OnAttr2Changing(global::System.String value);
        partial void OnAttr2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Attr3
        {
            get
            {
                return _Attr3;
            }
            set
            {
                OnAttr3Changing(value);
                ReportPropertyChanging("Attr3");
                _Attr3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Attr3");
                OnAttr3Changed();
            }
        }
        private global::System.String _Attr3;
        partial void OnAttr3Changing(global::System.String value);
        partial void OnAttr3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Attr4
        {
            get
            {
                return _Attr4;
            }
            set
            {
                OnAttr4Changing(value);
                ReportPropertyChanging("Attr4");
                _Attr4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Attr4");
                OnAttr4Changed();
            }
        }
        private global::System.String _Attr4;
        partial void OnAttr4Changing(global::System.String value);
        partial void OnAttr4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DictLangId
        {
            get
            {
                return _DictLangId;
            }
            set
            {
                OnDictLangIdChanging(value);
                ReportPropertyChanging("DictLangId");
                _DictLangId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DictLangId");
                OnDictLangIdChanged();
            }
        }
        private Nullable<global::System.Int32> _DictLangId;
        partial void OnDictLangIdChanging(Nullable<global::System.Int32> value);
        partial void OnDictLangIdChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="YusongCompanyModel", Name="ProductClass")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProductClass : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProductClass object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="sort">Initial value of the sort property.</param>
        /// <param name="dictLangId">Initial value of the DictLangId property.</param>
        /// <param name="parentId">Initial value of the ParentId property.</param>
        public static ProductClass CreateProductClass(global::System.Int32 id, global::System.Int32 sort, global::System.Int32 dictLangId, global::System.Int32 parentId)
        {
            ProductClass productClass = new ProductClass();
            productClass.Id = id;
            productClass.sort = sort;
            productClass.DictLangId = dictLangId;
            productClass.ParentId = parentId;
            return productClass;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String No
        {
            get
            {
                return _No;
            }
            set
            {
                OnNoChanging(value);
                ReportPropertyChanging("No");
                _No = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("No");
                OnNoChanged();
            }
        }
        private global::System.String _No;
        partial void OnNoChanging(global::System.String value);
        partial void OnNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 sort
        {
            get
            {
                return _sort;
            }
            set
            {
                OnsortChanging(value);
                ReportPropertyChanging("sort");
                _sort = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sort");
                OnsortChanged();
            }
        }
        private global::System.Int32 _sort;
        partial void OnsortChanging(global::System.Int32 value);
        partial void OnsortChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DictLangId
        {
            get
            {
                return _DictLangId;
            }
            set
            {
                OnDictLangIdChanging(value);
                ReportPropertyChanging("DictLangId");
                _DictLangId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DictLangId");
                OnDictLangIdChanged();
            }
        }
        private global::System.Int32 _DictLangId;
        partial void OnDictLangIdChanging(global::System.Int32 value);
        partial void OnDictLangIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ParentId
        {
            get
            {
                return _ParentId;
            }
            set
            {
                OnParentIdChanging(value);
                ReportPropertyChanging("ParentId");
                _ParentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentId");
                OnParentIdChanged();
            }
        }
        private global::System.Int32 _ParentId;
        partial void OnParentIdChanging(global::System.Int32 value);
        partial void OnParentIdChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="YusongCompanyModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static User CreateUser(global::System.Int32 id)
        {
            User user = new User();
            user.Id = id;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String passwd
        {
            get
            {
                return _passwd;
            }
            set
            {
                OnpasswdChanging(value);
                ReportPropertyChanging("passwd");
                _passwd = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("passwd");
                OnpasswdChanged();
            }
        }
        private global::System.String _passwd;
        partial void OnpasswdChanging(global::System.String value);
        partial void OnpasswdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String QQ
        {
            get
            {
                return _QQ;
            }
            set
            {
                OnQQChanging(value);
                ReportPropertyChanging("QQ");
                _QQ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("QQ");
                OnQQChanged();
            }
        }
        private global::System.String _QQ;
        partial void OnQQChanging(global::System.String value);
        partial void OnQQChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mobile
        {
            get
            {
                return _Mobile;
            }
            set
            {
                OnMobileChanging(value);
                ReportPropertyChanging("Mobile");
                _Mobile = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mobile");
                OnMobileChanged();
            }
        }
        private global::System.String _Mobile;
        partial void OnMobileChanging(global::System.String value);
        partial void OnMobileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tel
        {
            get
            {
                return _Tel;
            }
            set
            {
                OnTelChanging(value);
                ReportPropertyChanging("Tel");
                _Tel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tel");
                OnTelChanged();
            }
        }
        private global::System.String _Tel;
        partial void OnTelChanging(global::System.String value);
        partial void OnTelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WeChat
        {
            get
            {
                return _WeChat;
            }
            set
            {
                OnWeChatChanging(value);
                ReportPropertyChanging("WeChat");
                _WeChat = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WeChat");
                OnWeChatChanged();
            }
        }
        private global::System.String _WeChat;
        partial void OnWeChatChanging(global::System.String value);
        partial void OnWeChatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Memo
        {
            get
            {
                return _Memo;
            }
            set
            {
                OnMemoChanging(value);
                ReportPropertyChanging("Memo");
                _Memo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Memo");
                OnMemoChanged();
            }
        }
        private global::System.String _Memo;
        partial void OnMemoChanging(global::System.String value);
        partial void OnMemoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DictLangId
        {
            get
            {
                return _DictLangId;
            }
            set
            {
                OnDictLangIdChanging(value);
                ReportPropertyChanging("DictLangId");
                _DictLangId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DictLangId");
                OnDictLangIdChanged();
            }
        }
        private Nullable<global::System.Int32> _DictLangId;
        partial void OnDictLangIdChanging(Nullable<global::System.Int32> value);
        partial void OnDictLangIdChanged();

        #endregion

    
    }

    #endregion

    
}
